version: '3.8'

services:

  db:
    container_name: full-cycle-db
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: docker
      MARIADB_DATABASE: fcdb
      MARIADB_PASSWORD: docker
    networks:
      - appNetwork

  app:
    build: ./
    container_name: app
    ports:
      - '3456:3456'
    entrypoint: wait-for db:3306 -t 40 -- pnpm start:dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db
    networks:
      - appNetwork

  proxy:
    build: ./nginx
    container_name: nginx-proxy
    ports:
     - '80:80'
    depends_on:
      - app
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge
